version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME} #set username from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} #set password from .env
      POSTGRES_DB: ${DB_NAME} #set database name from .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
